### ISSUE TITLE
Storyboard the First 'Chapter'

### ISSUE THREAD

**Issue by aceslowman** [aceslowman/ReactRPG#10]
Sketch out and wireframe the actions that the user will take throughout the first 'tutorial chapter', which should walk through all core mechanics of the game.

**Comment by mbroberts1019** [comment]
I have built out the passages through the opening scene. Player wakes up, starting the game and is able to progress from being inside, going outside and going to town.

Still need to make the 'broken axe' item transfer to the players inventory when it gets pick up (if it gets picked up).  

Next scene should be the town and including the beginning of a quest. Also think that we could perhaps have the first battle sequence on the way to town.

**Comment by igerm96** [comment]
Passages and actions for first portion of the story are now set and done.
