### ISSUE TITLE
Create Passages and Actions in DB

### ISSUE THREAD

**Issue by mbroberts1019** [aceslowman/ReactRPG#16]
### Set up a few passages and actions to start testing

* Create 3-4 passages to begin story line
* Create action options to navigate between passages
* Try to implement the first few within Game Container

**Comment by mbroberts1019** [comment]
#### As of 6/3: 
* Still need to fine tune actions and create a list of 10-12 actions we want to have. 
* Change "actions" to"type" and update schemas. 

Passages are being pulled into game, need to build a bunch of passages.

**Comment by igerm96** [comment]
Mike and i have gone through an edited all actions and passages and have tested each loop in passages and actions.
