### ISSUE TITLE
Manually enter some documents in each collection

### ISSUE THREAD

**Issue by aceslowman** [aceslowman/ReactRPG#3]
For each of the following collections, generate 5 documents:

* PlayerCharacters
* NPCs
* Items
* Locations

**Comment by mbroberts1019** [comment]
Here is a link to a text based game creation in Unity and C#. Helpful for thinking about game design: [Unity C# Scripting](https://unity3d.com/learn/tutorials/topics/scripting/introduction-and-goals?playlist=17117
)
