### ISSUE TITLE
Create the PlayerStatBox Component

### ISSUE THREAD

**Issue by aceslowman** [aceslowman/ReactRPG#8]

**Comment by mbroberts1019** [comment]
Created a basic stats box. Realizing we should discuss how we are going to structure our styles and how we will name things.  This will be a good first thing to pull data into

`import React from "react";

const statBoxStyle = {
    borderRadius : '4px',
    backgroundColor: 'beige',
    borderStyle: 'solid',
    fontFamily: 'monospace',
    height: '100%',
    width: '20%',
    display: 'flex',
    flexWrap: 'wrap'
}

const statStyle = {
    textAlign: 'left',
    width: '50%',
    fontSize: '1rem'
}

const titleStyle = {
    width : '100%',
    fontSize: '2rem'
}

export default class PlayerStatBox extends React.Component{
    constructor(props){
        super(props);
        this.state = {
        }
    }

    render(){
        return(
            <div style= {statBoxStyle}>
                <h2 style = {titleStyle}>Player Stats</h2>
                    <div style= {statStyle}>
                        <h3 >HP: data</h3>
                        <h3 >AP: data</h3>
                    </div>
                    <div style= {statStyle} >
                        <ul ><h3>Items:</h3>
                            <li><h4>1st item</h4></li>
                            <li><h4>2nd Item</h4></li>
                            <li><h4>3rd Item</h4></li>
                        </ul>
                    </div>    
            </div>
        )
    }
}`
